import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { reports, tenants } from "@/lib/db/schema";
import { requireUser } from "@/lib/guards";
import { reportStats } from "@/lib/report-html";
import { INCIDENT_TYPE_META } from "@/lib/constants";
import PDFDocument from "pdfkit";

export const dynamic = "force-dynamic";

const TEAL = "#0f766e";
const INK = "#0f172a";
const MUTED = "#64748b";

type ReportData = {
  year?: number;
  month?: number;
  generatedAt?: number;
  generatedBy?: string | null;
  stats?: Record<string, number | undefined>;
  breakdown?: {
    byType?: Record<string, { count: number; lostDays: number; restrictedDays: number }>;
    totalLostDays?: number;
    totalRestrictedDays?: number;
  };
  training?: Record<string, number | undefined>;
};

function renderPdf(data: ReportData, title: string, tenantName: string, period: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48, info: { Title: title, Author: "HSE Dashboard" } });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    fillPages(doc, title, tenantName, period, data);

    doc.end();
  });
}

function fillPages(
  doc: PDFKit.PDFDocument,
  title: string,
  tenantName: string,
  period: string,
  data: ReportData
) {
  const s = data.stats ?? {};
  const byType = data.breakdown?.byType ?? {};

  doc.font("Helvetica-Bold").fontSize(10).fillColor(MUTED).text("HSE DASHBOARD", { characterSpacing: 1.5 });
  doc.moveDown(1);
  doc.font("Helvetica-Bold").fontSize(22).fillColor(INK).text(title, { align: "left" });
  doc.font("Helvetica").fontSize(12).fillColor(MUTED).text(`Reporting period: ${period}`);
  doc.font("Helvetica").fontSize(12).fillColor(TEAL).text(tenantName);
  doc.moveDown(2);

  doc.fontSize(14).fillColor(INK).text("Executive summary");
  doc.moveDown(0.5);

  const summary: [string, string][] = [
    ["Man-hours", (s.totalManhours ?? 0).toLocaleString()],
    ["Incidents", String(s.totalIncidents ?? 0)],
    ["Lost time injuries (LTI)", String(s.ltiCount ?? 0)],
    ["First aid cases", String(s.firstAid ?? 0)],
    ["Near misses", String(s.nearMiss ?? 0)],
    ["Recordable cases", String(s.recordable ?? 0)],
    ["LTI rate", (s.ltir ?? 0).toFixed(2)],
    ["TRIR", (s.trir ?? 0).toFixed(2)],
    ["Open findings", String(s.openFindings ?? 0)],
    ["Closed findings", String(s.closedFindings ?? 0)],
    ["TBT attendees", (s.totalTBT ?? 0).toLocaleString()],
    ["Inductions", String(s.totalInductions ?? 0)],
    ["Trainings on file", String(s.totalTrainings ?? 0)],
    ["Active permits", String(s.activePermits ?? 0)],
  ];
  drawKvTable(doc, summary, [380, 90]);

  doc.addPage();

  doc.font("Helvetica-Bold").fontSize(14).fillColor(INK).text("Incident breakdown");
  doc.moveDown(0.5);
  const header: [string, string, string, string] = ["Type", "Count", "Lost days", "Restricted days"];
  const rows = Object.entries(byType).length
    ? Object.entries(byType).map(
        ([type, v]): [string, string, string, string] => [
          INCIDENT_TYPE_META[type]?.label ?? type,
          String(v.count),
          String(v.lostDays),
          String(v.restrictedDays),
        ]
      )
    : [["No incidents recorded.", "", "", ""] as [string, string, string, string]];
  drawTable(doc, header, rows, [270, 90, 70, 70]);

  doc.moveDown(1.5);
  doc.font("Helvetica-Bold").fontSize(14).fillColor(INK).text("Safety performance");
  doc.moveDown(0.5);
  const perf: [string, string][] = [
    ["Lost days", String(data.breakdown?.totalLostDays ?? 0)],
    ["Restricted days", String(data.breakdown?.totalRestrictedDays ?? 0)],
    ["Sessions", String(s.tbtSessions ?? 0)],
  ];
  drawKvTable(doc, perf, [380, 90]);

  doc.moveDown(2);
  doc.font("Helvetica").fontSize(9).fillColor(MUTED).text(`Generated by HSE Dashboard · ${new Date().toLocaleString()}`, { align: "left" });
}

function drawKvTable(doc: PDFKit.PDFDocument, rows: [string, string][], colWidths: [number, number]) {
  const left = doc.page.margins.left;
  let y = doc.y;
  const rowH = 20;
  const [c0, c1] = colWidths;
  doc.font("Helvetica-Bold").fontSize(10);
  doc.fillColor("#e2e8f0").rect(left, y, c0 + c1, 22).fill();
  doc.fillColor(INK).text("Metric", left + 8, y + 6, { width: c0 - 8 });
  doc.text("Value", left + c0, y + 6, { width: c1 - 8, align: "right" });
  y += 22;
  doc.font("Helvetica").fontSize(10);
  for (const [k, v] of rows) {
    if (y > doc.page.height - doc.page.margins.bottom - 20) {
      doc.addPage();
      y = doc.y;
    }
    doc.fillColor(INK).text(k, left + 8, y + 6, { width: c0 - 8 });
    doc.fillColor(INK).text(v, left + c0, y + 6, { width: c1 - 8, align: "right" });
    doc.moveTo(left, y + 20).lineTo(left + c0 + c1, y + 20).strokeColor("#e2e8f0").lineWidth(0.75).stroke();
    y += rowH;
  }
  doc.y = y + 6;
}

function drawTable(doc: PDFKit.PDFDocument, header: [string, string, string, string], rows: [string, string, string, string][], widths: [number, number, number, number]) {
  const left = doc.page.margins.left;
  let y = doc.y;
  const rowH = 20;
  drawRow(doc, header, y, widths, left, true);
  y += rowH;
  for (const r of rows) {
    if (y > doc.page.height - doc.page.margins.bottom - 20) {
      doc.addPage();
      y = doc.page.margins.top;
    }
    drawRow(doc, r, y, widths, left, false);
    y += rowH;
  }
  doc.y = y;
}

function drawRow(doc: PDFKit.PDFDocument, cells: string[], y: number, widths: [number, number, number, number], left: number, isHeader: boolean) {
  doc.font(isHeader ? "Helvetica-Bold" : "Helvetica").fontSize(10);
  let x = left;
  cells.forEach((cell, i) => {
    if (isHeader) {
      doc.fillColor(TEAL).text(cell, x + 6, y + 6, { width: widths[i] - 12, align: i === 0 ? "left" : "right" });
    } else {
      doc.fillColor(INK).text(cell, x + 6, y + 6, { width: widths[i] - 12, align: i === 0 ? "left" : "right" });
    }
    doc.moveTo(x, y + 20).lineTo(x + widths[i], y + 20).strokeColor("#e2e8f0").lineWidth(0.75).stroke();
    x += widths[i];
  });
  if (isHeader) {
    doc.moveTo(left, y).lineTo(left + widths.reduce((a, b) => a + b, 0), y).strokeColor(TEAL).lineWidth(1).stroke();
  }
}

export async function GET(_req: Request, ctx: { params: Promise<{ id: string }> }) {
  await requireUser();
  const { id } = await ctx.params;

  const report = db.select().from(reports).where(eq(reports.id, id)).get();
  if (!report) {
    return Response.json({ error: "Report not found" }, { status: 404 });
  }
  const tenant = db.select().from(tenants).where(eq(tenants.id, report.tenantId)).get();
  const r = reportStats(report) as ReportData;
  const period = report.startDate
    ? new Date(report.startDate).toLocaleDateString("en-US", { month: "long", year: "numeric" })
    : new Date(r.generatedAt ?? report.createdAt).toLocaleDateString("en-US", { month: "long", year: "numeric" });

  const buffer = await renderPdf(r, report.title, tenant?.name ?? "HSE", period);

  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Length": String(buffer.byteLength),
      "Content-Disposition": `attachment; filename="${report.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf"`,
    },
  });
}